// Generated by CoffeeScript 1.3.3
(function() {
  var cb;

  cb = window.ContentBase || (window.ContentBase = {});

  cb.Plugin = {
    init: function() {
      $('.content-base img').each(cb.Plugin.fixImage);
    },
    fixImage: function(index, img) {
      var $img, $new;
      console.log("fixImage", arguments);
      $img = $(img);
      $new = $("<figure data-index=\"" + index + "\">\n	<img src=\"" + ($img.attr('src')) + "\" />\n</figure>");
      if ($img.attr('alt') !== '') {
        $new.append("<figcaption>" + ($img.attr('alt')) + "</figcaption>");
      }
      $new.attr('class', $img.attr('class'));
      $new.addClass('image');
      $(img).replaceWith($new);
    }
  };

  cb.Plugin.init();

}).call(this);
